name: Release

on:
  schedule:
    - cron: "40 3 * * 5"
  push:
    tags:
      - "v*"
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v6
        with:
          go-version-file: "go.mod"

      - name: Setup Node.js
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        uses: actions/setup-node@v7
        with:
          node-version: "lts/*"

      - name: Install UPX
        run: |
          sudo apt-get update
          sudo apt-get install -y upx

      - name: Install Cosign
        uses: sigstore/cosign-installer@v4.1.2

      - name: Install Syft
        uses: anchore/sbom-action@v0
        with:
          upload-release-assets: false

      - name: Run GolangCI-Lint
        uses: golangci/golangci-lint-action@v9
        with:
          args: --timeout=10m

      - uses: golang/govulncheck-action@v1
        with:
          repo-checkout: false

      - name: Check if module is tidy
        run: |
          go mod tidy
          git diff --exit-code go.mod go.sum || (echo "go.mod/go.sum is not tidy. Please run 'go mod tidy' and commit the changes." && exit 1)

      - name: Verify build
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        uses: goreleaser/goreleaser-action@v7
        with:
          version: latest
          args: release --snapshot --clean
        env:
          COSIGN_YES: "true"
          GOPRIVATE: github.com/mizuchilabs/*

      - name: Run Semantic Release
        id: semantic
        if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          PREV_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
          npx semantic-release --plugins "@semantic-release/commit-analyzer,@semantic-release/release-notes-generator,@semantic-release/github"
          git fetch --tags --force
          NEW_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")

          if [ "$PREV_TAG" != "$NEW_TAG" ] && [ -n "$NEW_TAG" ]; then
            echo "released=true" >> "$GITHUB_OUTPUT"
            echo "New release $NEW_TAG generated"
          else
            echo "released=false" >> "$GITHUB_OUTPUT"
            echo "No new release generated"
          fi

      - name: Run GoReleaser
        if: github.event_name == 'push' || steps.semantic.outputs.released == 'true'
        uses: goreleaser/goreleaser-action@v7
        with:
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_YES: "true"
